#!/usr/bin/env bash
# Temporary herdr agent-detection override for claude.
#
# herdr 0.9.1 misses some open permission dialogs (see README.md). Each
# override is herdr's own cached remote manifest plus one rule from
# <agent>.rule.toml, with a version suffix. It is generated, never copied into
# the repo, so re-running `install` rebases it on the current upstream rules.
#
#   herdr-overrides.sh verify [--upstream] [agent...]   check the fixtures (no server change)
#   herdr-overrides.sh install [agent...]               verify, write, reload herdr
#   herdr-overrides.sh uninstall [agent...]             remove our files, reload herdr
#   herdr-overrides.sh check [agent...]                 is the override still needed?
#   herdr-overrides.sh build <dir> [agent...]           write the overrides into <dir>
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
REMOTE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/herdr/agent-detection/remote"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/herdr/agent-detection"
MARK="# agent-watch-override"
SUFFIX="900"
ALL_AGENTS=(claude)

# Fixtures: "<file> <expected>", expected is "blocked" or "not-blocked".
fixtures() {
	local fx="$REPO/pkg/agents/testdata" td="$HERE/testdata"
	case "$1" in
	claude)
		cat <<EOF
$fx/claude/permission-bash.txt blocked
$fx/claude/permission-edit.txt blocked
$fx/claude/permission-webfetch.txt blocked
$fx/claude/permission-write-numbered-list.txt blocked
$fx/claude/permission-bash-dont-ask-again.txt blocked
$fx/claude/plan-approval.txt blocked
$fx/claude/question-multiple.txt blocked
$td/claude-webfetch-fresh.txt blocked
$td/claude-webfetch-stale-box.txt blocked
$td/claude-bash-stale-box.txt blocked
$fx/claude/no-menu-working.txt not-blocked
$td/claude-idle-typed-prompt.txt not-blocked
$fx/claude/no-menu-idle-numbered-list.txt not-blocked
$fx/claude/no-menu-working-numbered-list.txt not-blocked
EOF
		;;
	*) echo "unknown agent: $1" >&2; exit 2 ;;
	esac
}

die() { echo "herdr-overrides: $*" >&2; exit 1; }

remote_version() {
	local f="$REMOTE_DIR/$1.toml"
	[ -f "$f" ] || die "no cached remote manifest $f (run: herdr server update-agent-manifests)"
	sed -n 's/^version = "\([0-9.]*\)"$/\1/p' "$f" | head -n 1
}

# Writes <dir>/<agent>.toml: remote manifest, version bumped, our rule appended.
build_one() {
	local agent="$1" dir="$2" base
	base="$(remote_version "$agent")"
	[ -n "$base" ] || die "$agent: remote manifest has no numeric version"
	mkdir -p "$dir"
	{
		awk -v old="version = \"$base\"" -v new="version = \"$base.$SUFFIX\"" \
			'!done && $0 == old { print new; done = 1; next } { print }' "$REMOTE_DIR/$agent.toml"
		printf '\n%s base=%s rule=%s.rule.toml\n' "$MARK" "$base" "$agent"
		printf '# Generated by tools/herdr-overrides in the agent-watch repo. Remove it with\n'
		printf '# `tools/herdr-overrides/herdr-overrides.sh uninstall` once herdr handles this upstream.\n'
		cat "$HERE/$agent.rule.toml"
	} >"$dir/$agent.toml"
}

# Runs the fixtures through `herdr agent explain --file` with XDG_CONFIG_HOME=$1
# (an empty config dir means: upstream rules only). Prints a table; returns 1 on
# any mismatch.
run_fixtures() {
	local xdg="$1" agent="$2" fail=0 file want got
	while read -r file want; do
		[ -f "$file" ] || die "missing fixture $file"
		got="$(XDG_CONFIG_HOME="$xdg" herdr agent explain --file "$file" --agent "$agent" --json |
			python3 -c 'import json,sys; d=json.load(sys.stdin); m=d.get("matched_rule") or {}; print(d.get("state"), m.get("id","-"))')"
		local state="${got%% *}" rule="${got#* }" ok="ok"
		if [ "$want" = blocked ] && [ "$state" != blocked ]; then ok="FAIL"; fail=1; fi
		if [ "$want" = not-blocked ] && [ "$state" = blocked ]; then ok="FAIL"; fail=1; fi
		printf '  %-4s %-7s want %-11s got %-8s rule %-28s %s\n' "$ok" "$agent" "$want" "$state" "$rule" "${file#"$REPO"/}"
	done < <(fixtures "$agent")
	return $fail
}

agents_or_all() { if [ $# -gt 0 ]; then echo "$@"; else echo "${ALL_AGENTS[@]}"; fi; }

cmd_verify() {
	local upstream=0
	if [ "${1:-}" = "--upstream" ]; then upstream=1; shift; fi
	local tmp fail=0
	tmp="$(mktemp -d)"
	for agent in $(agents_or_all "$@"); do
		if [ $upstream = 1 ]; then
			echo "$agent: upstream rules only (manifest $(remote_version "$agent"))"
		else
			build_one "$agent" "$tmp/herdr/agent-detection"
			echo "$agent: upstream $(remote_version "$agent") + $agent.rule.toml"
		fi
		run_fixtures "$tmp" "$agent" || fail=1
	done
	rm -rf "$tmp"
	return $fail
}

cmd_install() {
	cmd_verify "$@" || die "fixtures failed with the generated override; nothing installed"
	for agent in $(agents_or_all "$@"); do
		local dst="$CONFIG_DIR/$agent.toml"
		if [ -f "$dst" ] && ! grep -qF "$MARK" "$dst"; then
			die "$dst exists and was not written by this tool; refusing to overwrite it"
		fi
		build_one "$agent" "$CONFIG_DIR"
		echo "installed $dst"
	done
	herdr server reload-agent-manifests | python3 -c '
import json, sys
wanted = set(sys.argv[1:])
for m in json.load(sys.stdin)["result"]["manifests"]:
    if m["agent"] in wanted:
        print("  %-7s %-15s %s" % (m["agent"], m["source_kind"], m["active_version"]))' $(agents_or_all "$@")
}

cmd_uninstall() {
	for agent in $(agents_or_all "$@"); do
		local dst="$CONFIG_DIR/$agent.toml"
		if [ -f "$dst" ] && grep -qF "$MARK" "$dst"; then
			rm -f "$dst"
			echo "removed $dst"
		elif [ -f "$dst" ]; then
			echo "left $dst alone: not written by this tool" >&2
		fi
	done
	herdr server reload-agent-manifests | python3 -c '
import json, sys
wanted = set(sys.argv[1:])
for m in json.load(sys.stdin)["result"]["manifests"]:
    if m["agent"] in wanted:
        print("  %-7s %-15s %s" % (m["agent"], m["source_kind"], m["active_version"]))' $(agents_or_all "$@")
}

cmd_check() {
	local tmp stale=0
	tmp="$(mktemp -d)"
	for agent in $(agents_or_all "$@"); do
		local dst="$CONFIG_DIR/$agent.toml" base now
		now="$(remote_version "$agent")"
		if [ ! -f "$dst" ] || ! grep -qF "$MARK" "$dst"; then
			echo "$agent: no override installed (upstream $now)"
			continue
		fi
		base="$(sed -n "s/^$MARK base=\([0-9.]*\) .*/\1/p" "$dst")"
		if [ "$base" != "$now" ]; then
			echo "$agent: upstream manifest moved $base -> $now since install: the override hides the new upstream rules. Re-run install to rebase, or uninstall if the check below passes."
			stale=1
		else
			echo "$agent: override based on the current upstream manifest $now"
		fi
		if run_fixtures "$tmp" "$agent" >/dev/null; then
			echo "$agent: upstream alone now detects every fixture -> the override can be removed: $0 uninstall $agent"
		else
			echo "$agent: upstream alone still misses some dialogs -> keep the override (details: $0 verify --upstream $agent)"
		fi
	done
	rm -rf "$tmp"
	return $stale
}

main() {
	command -v herdr >/dev/null || die "herdr not found in PATH"
	local cmd="${1:-}"; shift || true
	case "$cmd" in
	build) [ $# -ge 1 ] || die "usage: build <dir> [agent...]"; local dir="$1"; shift; for a in $(agents_or_all "$@"); do build_one "$a" "$dir"; echo "wrote $dir/$a.toml"; done ;;
	verify) cmd_verify "$@" ;;
	install) cmd_install "$@" ;;
	uninstall) cmd_uninstall "$@" ;;
	check) cmd_check "$@" ;;
	*) sed -n '2,13p' "$0" >&2; exit 2 ;;
	esac
}

main "$@"
